import type { SimpleIcon } from "simple-icons";
import {
	siAntdesign,
	siAnthropic,
	siAstro,
	siBetterauth,
	siBootstrap,
	siBun,
	siClaude,
	siCloudflare,
	siCursor,
	siDocker,
	siDrizzle,
	siExpo,
	siExpress,
	siFastify,
	siFigma,
	siFramer,
	siGit,
	siGithub,
	siGithubactions,
	siGooglecloud,
	siHermes,
	siLaravel,
	siMongodb,
	siMui,
	siMysql,
	siNestjs,
	siNextdotjs,
	siNginx,
	siNodedotjs,
	siOllama,
	siPnpm,
	siPostgresql,
	siPrisma,
	siReact,
	siReactquery,
	siRedis,
	siRedux,
	siShadcnui,
	siSupabase,
	siTailwindcss,
	siTypescript,
	siVercel,
	siVite,
	siXendit,
} from "simple-icons";

const catalog: Record<string, SimpleIcon> = {
	antdesign: siAntdesign,
	anthropic: siAnthropic,
	astro: siAstro,
	betterauth: siBetterauth,
	bootstrap: siBootstrap,
	bun: siBun,
	claude: siClaude,
	cloudflare: siCloudflare,
	cursor: siCursor,
	docker: siDocker,
	drizzle: siDrizzle,
	expo: siExpo,
	express: siExpress,
	fastify: siFastify,
	figma: siFigma,
	framer: siFramer,
	git: siGit,
	github: siGithub,
	githubactions: siGithubactions,
	googlecloud: siGooglecloud,
	hermes: siHermes,
	laravel: siLaravel,
	mongodb: siMongodb,
	mui: siMui,
	mysql: siMysql,
	nestjs: siNestjs,
	nextdotjs: siNextdotjs,
	nginx: siNginx,
	nodedotjs: siNodedotjs,
	ollama: siOllama,
	pnpm: siPnpm,
	postgresql: siPostgresql,
	prisma: siPrisma,
	react: siReact,
	reactquery: siReactquery,
	redis: siRedis,
	redux: siRedux,
	shadcnui: siShadcnui,
	supabase: siSupabase,
	tailwindcss: siTailwindcss,
	typescript: siTypescript,
	vercel: siVercel,
	vite: siVite,
	xendit: siXendit,
};

export function getStackIcon(slug?: string) {
	if (!slug) return null;
	return catalog[slug] ?? null;
}
